language: php
sudo: required
dist: trusty

php:
  - '7.1'
  - '7.2'
  - '7.3'

addons:
  chrome: stable

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
